### ISSUE TITLE
csh script is not csh friendly

### ISSUE THREAD

**Issue by ScarabMonkey** [nysbc/Anisotropy#4]
I am trying to use this program on our cluster where we use the TCSH shell ... unfortunately I get the error:
"activate: No such file or directory."
Also this seems to be creating a new shell each time I execute the script.

It seems that the script does not have #!/bin/csh as the first line - so the local shell assumes the script is written in its own language. For people using bash this will will 'just work' but for anyone else this is bound to fail.

I see two problems here:

1. the file is named .csh but is not actually a functioning csh shell script
2. assumption that the user is on bash

**Comment by ScarabMonkey** [comment]
I have created a .sh version of this script which calls the 'sh' interpreter - that version works for us on our CentOS 6 cluster where users have TCSH shell. I expect it will also work for everyone else, so  I would recommend removing the .csh script as well as adding my new .sh version

**Comment by ScarabMonkey** [comment]
The current .csh script will only work for people using bash or zsh - as 'activate' specifically states: "Only bash and zsh are supported".

**Comment by nysbc** [comment]
Thank you for pointing that out! Wait, so does that mean you are still having problem with your modified .sh script?

**Comment by nysbc** [comment]
I have merged your .sh to the base. Thanks alot of the input!
