### ISSUE TITLE
3DFSC Processing Server password protected zip files

### ISSUE THREAD

**Issue by mplockhartuom** [nysbc/Anisotropy#5]
I've run the 3DFSC server and everything went ran well but when I download the zip file it asks for a password to unzip the folder. This occurs on windows (10) and linux (ubuntu 16.04).

I've run a couple of different runs and they both give the same results. Any help would be much appreciated.

just to say I have got this working on my own box from the git version.

**Comment by nysbc** [comment]
In the results page, the last table entry right below your download link contains the password for your zip file. Hope this helps!

**Comment by mplockhartuom** [comment]
Yep, totally missed that. Thanks.
